language: python
python:
    - "2.7"
virtualenv:
    system_site_packages: true
# install scipy and numpy
# cvxopt is for examples
before_install:
    - sudo apt-get install python-numpy python-scipy python-cvxopt
# install dependencies
install:
    - pip install ply coverage
    - cd scripts; sudo ./get_ecos.sh
    - cd ..; sudo python setup.py install
# command to run tests
script:
    - cd scripts; ./run_examples.sh
    - cd ..; nosetests --with-cover --cover-package=src
